name: first_workflow
on: 
  workflow_dispatch:   
jobs:
  Build-job:
   runs-on: jag-devops
   steps:
     - name : task1 to print OS detsils
       run: uname -a
     - name : task2 to print hostname
       run: hostname
     - name : step 3
       run : sleep 30
     - name : End job1  
       run : |
         touch /tmp/jagfile1
         echo "Build job completed"
         echo "Value for user1 and servername are ${{VARS.USER1}} ${{VARS.server_name}}"
         
  Test-job:
    runs-on: ubuntu-latest
    steps:
      - name : task1 to print OS detsils
        run: uname -a
      - name : task2 to print hostname
        run: hostname
      - name : step 3
        run : sleep 30
      - name : End job1  
        run : echo "Test job completed" 
