name: first_workflow
on: 
  push:
    branches:
     - main
     - dev
  workflow_dispatch:   
jobs:
  job1:
   runs-on: ubuntu-latest
   steps:
     - name : task1 to print OS detsils
       run: uname -a
     - name : task2 to print hostname
       run: hostname
  
