name: Test_env_Var
on:
  workflow_dispatch:
    inputs:
      deployTo:
        type: choice
        description: The environment you are deploying to
        options:
          - "dev"
          - "prod"

   

jobs:
  build:
    runs-on: ubuntu-latest 
    environment: ${{ inputs.deployTo }}
    steps:
      - name: Check environment access
        run: |
          echo "${{ inputs.deployTo }}" 
          echo "${{ VARS.server_name  }}" 
    
