name: w3flow
on:
  push:
    branches:
      - main

jobs:
  build:
    environment: dev
    runs-on: jag-devops
    
    steps:
      - name: step1
        run: |
         echo "test ste1"
         sleep 10
  test:
    environment: dev
    runs-on: jag-devops
    needs: build
    steps:
      - name: step1
        run: |
         echo "test ste1"
         sleep 10
  deploy:
    environment: dev
    runs-on: jag-devops
    needs: test
    steps:
      - name: step1
        run: |
         echo "test ste1"
         sleep 10                
