name: w3flow
on:
  push:
    branches:
      - main

jobs:
  build:
    environment: dev
    runs-on: jag-devops
    
    steps:
      - name: step1
        #continue-on-error: true
        run: |
         echo "test ste1"
         sleep 10
      - name: step2
        run: echo "running step 2"
      - name: step3
        run: echo "running step 3"        
  test:
    environment: dev
    runs-on: jag-devops
    needs: [build,build2]
    steps:
      - name: step1
        run: |
         echo "test ste1"
         sleep 10
  test2:
    environment: dev
    runs-on: jag-devops
    needs: build
    steps:
      - name: step1
        run: |
         echo "test ste1"
         sleep 10         
  build2:
    environment: dev
    runs-on: jag-devops

    steps:
      - name: step1
        run: |
         echo "test ste1"
         sleep 10
  deploy:
    environment: dev
    runs-on: jag-devops
    needs: test
    steps:
      - name: step1
        run: |
         echo "test ste1"
         sleep 10                
  notification:
    environment: dev
    runs-on: jag-devops
    needs: build
    if: ${{ needs.build.result == 'failure' || failure() }}
    steps:
      - name: step1
        run: |
         echo "build failed"
         
