name: workflow2
on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main
env:
  USER1: jagadish
jobs:
  build:
    env:
      USER2: JAG
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1 
      - name: step 2 
        env:
          USER3: MUN
        run: |
         ls -l
         echo "github repo name is : ${{GITHUB.REPOSITORY}} and user is ${{GITHUB.ACTOR}}"
         echo "value for USER is : $USER1 , $USER2 , $USER3"
         pwd
         javaa -version
      -  run: echo "print valur of user 3 $USER3" 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1 
      - name: step 2 
        run: |
         ls -l
         echo "github repo name is : ${{GITHUB.REPOSITORY}} and user is ${{GITHUB.ACTOR}}"
         echo "value for USER is : $USER1 , $USER2 , $USER3"
         pwd    
    
