name: workflow2
on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main
env:
  USER1: jagadish
jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1 
      - name: step 2 
        env:
          USER3: MUN
        run: |
         ls -l
         echo "github repo name is : ${{GITHUB.REPOSITORY}} and user is ${{GITHUB.ACTOR}}"
         echo "value for USER is : $USER1 , $USER2 , $USER3"
         echo "Value for user1 and servername are ${{VARS.USER1}} ${{VARS.server_name}}"
         pwd
         java -version
  test:
    environment: prod
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v4.1.1 
       - name: step 2 
         run: |
          ls -l
          echo "github repo name is : ${{GITHUB.REPOSITORY}} and user is ${{GITHUB.ACTOR}}"
          echo "value for USER is : $USER1 , $USER2 , $USER3"
          echo "Value for user1 and servername are ${{VARS.USER1}} ${{VARS.server_name}}"
          pwd    
    
